trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      displayName: Build and push backend image
      inputs:
        containerRegistry: 'cncregistry'
        repository: 'cnc-backend'
        command: 'buildAndPush'
        Dockerfile: 'backend/Dockerfile'
        tags: 'latest'
    
    - task: Docker@2
      displayName: Build and push frontend image
      inputs:
        containerRegistry: 'cncregistry'
        repository: 'cnc-frontend'
        command: 'buildAndPush'
        Dockerfile: 'frontend/Dockerfile'
        tags: 'latest'

- stage: Deploy
  jobs:
  - job: DeployToAzure
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Backend'
      inputs:
        azureSubscription: 'YourAzureSubscription'
        appName: 'cnc-backend'
        containers: 'cncregistry.azurecr.io/cnc-backend:latest'
    
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Frontend'
      inputs:
        azureSubscription: 'YourAzureSubscription'
        appName: 'cnc-frontend'
        containers: 'cncregistry.azurecr.io/cnc-frontend:latest'