# Generated by Django 5.2 on 2025-06-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_materiasPrimas', '0001_initial'),
        ('sc_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('lote_tamanho', models.FloatField()),
                ('data_producao', models.DateField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='LoteMateriaPrimaConsumida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_consumida_mg', models.FloatField()),
                ('lote_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_materiasPrimas.lotemateriaprima')),
                ('lote_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_consumidas', to='sc_producao.loteproducao')),
            ],
        ),
    ]
