# Generated by Django 5.2 on 2025-06-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_materiasPrimas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_farmaceutica', models.CharField(choices=[('cápsula gelatina mole', 'Capsula Gelatina Mole'), ('cápsula mastigável', 'Capsula Mastigavel'), ('comprimido', 'Comprimido'), ('líquido', 'Liquido')], max_length=30)),
                ('quant_unid_padrao', models.IntegerField()),
                ('quant_kg_padrao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_mg', models.FloatField()),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='sc_produtos.formula')),
                ('lote_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_materiasPrimas.lotemateriaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('apresentacao', models.CharField(choices=[('Embalagem com 30 unidades', 'Embalagem 30'), ('Embalagem com 60 unidades', 'Embalagem 60'), ('Embalagem com 90 unidades', 'Embalagem 90'), ('Embalagem com 120 unidades', 'Embalagem 120')], max_length=30)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='sc_produtos.formula')),
            ],
        ),
    ]
