# Generated by Django 5.2 on 2025-05-02 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('quant_total_mg', models.FloatField()),
                ('quant_disponivel_mg', models.FloatField()),
                ('nota_fiscal', models.CharField(max_length=50)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_fornecedores.fornecedor')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc_materiasPrimas.materiaprima')),
            ],
        ),
    ]
