# Generated by Django 5.2 on 2025-06-30 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('cod_interno', models.IntegerField(auto_created=True, default=0, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('nota_fiscal', models.IntegerField(blank=True, null=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('dias_validade_apos_aberto', models.IntegerField(default=30)),
                ('embalagem_aberta', models.BooleanField(default=False)),
                ('data_abertura_embalagem', models.DateField(blank=True, null=True)),
                ('quantidade_disponivel', models.FloatField(default=0)),
                ('unidade_medida', models.CharField(default='kg', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('condicao_armazenamento', models.CharField(blank=True, max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('_status_interno', models.CharField(db_column='status', default='disponível', max_length=50)),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='sc_fornecedores.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(default='', max_length=50)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('nota_fiscal', models.CharField(max_length=50)),
                ('quant_recebida_kg', models.FloatField(default=0)),
                ('quant_disponivel_kg', models.FloatField(default=0)),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now)),
                ('aprovado_controle_qualidade', models.BooleanField(default=False)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('responsavel_aprovacao', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('local_armazenamento', models.CharField(blank=True, max_length=100)),
                ('condicoes_armazenamento', models.CharField(blank=True, max_length=255)),
                ('embalagem_original_aberta', models.BooleanField(default=False)),
                ('data_abertura_embalagem', models.DateField(blank=True, null=True)),
                ('codigo_rastreabilidade', models.CharField(blank=True, max_length=100)),
                ('fornecedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_fornecidos', to='sc_fornecedores.fornecedor')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='sc_materiasPrimas.materiaprima')),
            ],
            options={
                'verbose_name': 'Lote de Matéria Prima',
                'verbose_name_plural': 'Lotes de Matérias Primas',
                'unique_together': {('materia_prima', 'numero_lote')},
            },
        ),
    ]
