# Generated by Django 5.2 on 2025-06-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sc_materiasPrimas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='data_validade_efetiva',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='laudo',
        ),
    ]
