# Generated by Django 5.2 on 2025-06-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_materiasPrimas', '0002_remove_materiaprima_data_validade_efetiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='status',
            field=models.CharField(db_column='status', default='disponível', max_length=50),
        ),
        migrations.RenameField(
            model_name='materiaprima',
            old_name='status',
            new_name='_status_interno',
        ),
    ]
